### ISSUE TITLE
Published Federico's Portfolio on Github pages

### ISSUE THREAD

**Issue by Flunavgt** [Flunavgt/Federico-s_Portfolio#7]
On this assignment:

1. I updated the ReadMe file including a link to the online version.
2. Checked all links and different size screens for responsiveness.

The link to the online version: https://flunavgt.github.io/Federico-s_Portfolio/

**Comment by tufoinnkuo10** [comment]
## Status: Approved :heavy_check_mark:

Hi @Flunavgt 

Your project is complete! Great job for nailing it on the first try🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request✔️ 
- Validations correctly implemented✔️  
- successfully deployed✔️ 

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

![tufoin](https://media.giphy.com/media/HloNK1z39EkEQcreIo/giphy.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
